### ISSUE TITLE
Where you find the formula butterworth filter?

### ISSUE THREAD

**Issue by LiemFrans** [Grubleren/ButterworthFilter#1]

**Comment by Grubleren** [comment]
I have the formulas from a book I Danish

 

Jens

**Comment by LiemFrans** [comment]
can you give me a link of pdf book I Danish, thankyou for your attention.. :)

**Comment by Grubleren** [comment]
![billede 2](https://user-images.githubusercontent.com/16530000/45941937-ab297300-bfe0-11e8-9264-394e065d5706.jpg)
![billede 3](https://user-images.githubusercontent.com/16530000/45941938-ab297300-bfe0-11e8-8fc2-0e7058ad1619.jpg)
![billede 4](https://user-images.githubusercontent.com/16530000/45941939-ab297300-bfe0-11e8-9b8e-7b70f5ae49bc.jpg)
![billede 5](https://user-images.githubusercontent.com/16530000/45941940-abc20980-bfe0-11e8-8744-29235e944ada.jpg)
![billede](https://user-images.githubusercontent.com/16530000/45941941-abc20980-bfe0-11e8-99f5-693bb7ac0d0d.jpg)
