### ISSUE TITLE
Where can i find ipps-8.0.dll?

### ISSUE THREAD

**Issue by LiemFrans** [Grubleren/ButterworthFilter#2]
![image](https://user-images.githubusercontent.com/41262407/45930028-12fda080-bf84-11e8-8052-88b645620530.png)
where can i find that file?

**Comment by Grubleren** [comment]
Look here:

 

https://software.seek.intel.com/performance-libraries

 

regards Jens

**Comment by LiemFrans** [comment]
which one should be chosen
![image](https://user-images.githubusercontent.com/41262407/45934820-aeffca00-bfcd-11e8-9e44-e985058a85ca.png)

**Comment by Grubleren** [comment]
#2

Sendt fra min Sony Xperia™-smartphone

---- LiemFrans skrev ----

**Comment by LiemFrans** [comment]
I have installed IPP but it still hasn't been successfully executed,... where's is dll ?

**Comment by Grubleren** [comment]
Remember to use the repository IppWrapper

**Comment by Grubleren** [comment]
The dll’s are located here: C:\Program Files (x86)\IntelSWTools

 

You have to figure out yourself how to use the, I have used an older version, but the new ones should have the same interface

 

Jens
