### ISSUE TITLE
I Find the wrong formula in your code :) in GetComplexPoles

### ISSUE THREAD

**Issue by LiemFrans** [Grubleren/ButterworthFilter#3]
![image](https://user-images.githubusercontent.com/41262407/45934855-4bc26780-bfce-11e8-9160-f807c22d5913.png)
maybe you need to use this formula, or I'm wrong?

**Comment by LiemFrans** [comment]
![image](https://user-images.githubusercontent.com/41262407/45934882-a3f96980-bfce-11e8-9dcb-4996fcbedb84.png)
in this code . :)

**Comment by Grubleren** [comment]
Could be right 

Sendt fra min Sony Xperia™-smartphone

---- LiemFrans skrev ----

**Comment by Grubleren** [comment]
My code is right 

Sendt fra min Sony Xperia™-smartphone

---- LiemFrans skrev ----
